%YAML:1.0
---
camera_parameter: 
    CFG_MODE: 1
    TYPE: "MT9V022"
    SIZE: [640,480]
    BIT_WIDTH: 8
    FORMAT: [4,0]
    I2C_MODE: 1
    I2C_ADDR: "0x90"
    TRANS_LVL: 64

board_parameter: []

board_parameter_dev2: 
   - ["0xd7","0x4600","0x0100","0x01",["0x00"]]
   - ["0xd7","0x4600","0x0100","0x01",["0x05"]]

board_parameter_dev3_inf2: 
   - ["0xf3","0x0000","0x0000","0x00",[]]
   - ["0xf9","0x0000","0x0000","0x00",[]]

board_parameter_dev3_inf3: 
   - ["0xf3","0x0000","0x0000","0x00",[]]
   - ["0xf9","0x0000","0x0000","0x00",[]]

register_parameter: 
   - ["0x0003","0x01e0"]
   - ["0x0004","0x0280"]

register_parameter_dev3_inf2: 
   - ["0x0003","0x01e0"]
   - ["0x0004","0x0280"]

register_parameter_dev3_inf3: 
   - ["0x0003","0x01e0"]
   - ["0x0004","0x0280"]

