//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 USBTest.rc 使用
//
#define IDD_USBTEST_DIALOG              102
#define IDD_CONTROL_DIALOG              103
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       137
#define IDD_ABOUT_DIALOG                138
#define IDR_MENU2                       140
#define IDD_DATA_INFO_DIALOG            142
#define IDC_BUTTON_INIT                 1000
#define IDC_RICHEDIT_LOG                1001
#define IDC_BUTTON_PLAY                 1002
#define IDC_BUTTON_CLOSE                1003
#define IDC_BUTTON_STOP                 1004
#define IDC_STATIC_FRAME_CAPTRUE_COUNT  1005
#define IDC_STATIC_FRAME_READ_COUNT     1006
#define IDC_STATIC_DISPLAY              1007
#define IDC_EDIT1                       1008
#define IDC_EDIT_VID                    1008
#define IDC_CTRL_EDIT_1                 1008
#define IDC_MIPI_DATA_ROW_EDIT          1008
#define IDC_EDIT2                       1009
#define IDC_COMBO1                      1010
#define IDC_MIPI_DATA_COL_EDIT          1010
#define IDC_BUTTON_REG_READ             1011
#define IDC_BUTTON_REG_WRITE            1012
#define IDC_BUTTON_SCAN                 1013
#define IDC_EDIT4                       1014
#define IDC_EDIT5                       1015
#define IDC_COMBO2                      1016
#define IDC_COMBO_TYPE                  1016
#define IDC_COMBO3                      1017
#define IDC_COMBO4                      1018
#define IDC_BUTTON_OPEN                 1019
#define IDC_BUTTON_BYTE_CONV            1020
#define IDC_COMBO5                      1021
#define IDC_EDIT3                       1022
#define IDC_BUTTON_STOP2                1023
#define IDC_BUTTON_SHOT                 1023
#define IDC_STATIC_FRAME_READ_COUNT2    1024
#define IDC_STATIC_SHOT_TIME            1024
#define IDC_SCROLLBAR1                  1025
#define IDC_CHECK1                      1026
#define IDC_STATIC_IMU_INDEX            1027
#define IDC_STATIC_IMU_TIME             1028
#define IDC_STATIC_IMU_ACCX             1029
#define IDC_STATIC_IMU_ACCY             1030
#define IDC_STATIC_IMU_ACCZ             1031
#define IDC_STATIC_                     1032
#define IDC_STATIC_IMU_GYROX            1032
#define IDC_STATIC_IMU_GYROY            1033
#define IDC_STATIC_IMU_GYROZ            1034
#define IDC_STATIC_IMU_TIMP             1035
#define IDC_CHECK_IMU_EN                1036
#define IDC_EDIT6                       1037
#define IDC_EDIT7                       1038
#define IDC_BUTTON_USER_DATA_READ       1039
#define IDC_BUTTON_USAR_DATA_WRITE      1040
#define IDC_EDIT8                       1041
#define IDC_BUTTON_T                    1042
#define IDC_BUTTON_TEST                 1042
#define IDC_COMBO_FORMAT                1043
#define IDC_CHECK2                      1044
#define IDC_CHECK_SHOT                  1044
#define IDC_COMBO6                      1050
#define IDC_RADIO_DISPLAY               1051
#define IDC_EDIT13                      1052
#define IDC_CHECK_FULL_SCREEN           1053
#define IDC_BUTTON_LOAD                 1054
#define IDC_BUTTON_FRASH                1055
#define IDC_CHECK_IRCUT                 1056
#define IDC_STATIC_UUID                 1057
#define IDC_RADIO_SAVE_DATA             1058
#define IDC_RADIO_SAVE_IMAGE            1059
#define IDC_RADIO_SAVE_VIDEO            1060
#define IDC_RADIO1                      1061
#define IDC_RADIO_MODE_HORIZONTAL       1061
#define IDC_RADIO2                      1062
#define IDC_RADIO_MODE_VERTICAL         1062
#define IDC_STATIC_WEB_SITE             1062
#define IDC_CHECK_IRCUT2                1063
#define IDC_CHECK_WHITE_BALANCE         1063
#define IDC_STATIC_GITHUB               1063
#define IDC_STATIC_CPLD_KEY             1064
#define IDC_STATIC_CPLD_VERSION         1065
#define IDC_STATIC_USB_KEY              1066
#define IDC_STATIC_USB_VERSION          1067
#define IDC_OPEN_FILE                   1068
#define IDC_BUTTON1                     1069
#define IDC_SLIDER1                     1070
#define IDC_CTRL_SLIDER_1               1070
#define IDC_TEXT_EXPOSURE               1071
#define IDC_CTRL_LABEL_1                1071
#define IDC_GAIN                        1072
#define IDC_CTRL_LABEL_2                1072
#define IDC_SLIDER2                     1073
#define IDC_CTRL_SLIDER_2               1073
#define ID_CLOSE_CTRL                   1074
#define IDC_CTRL_EDIT_2                 1075
#define IDC_MIPI_DATA_ID_LABEL          1077
#define IDC_MIPI_DATA_ROW_LABEL         1078
#define IDC_CTRL_LABEL_3                1079
#define IDC_MIPI_DATA_COL_LABEL         1079
#define IDC_CTRL_SLIDER_3               1080
#define IDC_MIPI_DATA_ID_EDIT           1080
#define IDC_CTRL_EDIT_3                 1081
#define IDC_MIPI_CLOCK_LABEL            1081
#define IDC_MIPI_CLOCK_EDIT             1082
#define IDC_CTRL_LABEL_4                1085
#define IDC_CTRL_SLIDER_4               1086
#define IDC_CTRL_EDIT_4                 1087
#define IDC_CTRL_LABEL_5                1088
#define IDC_CTRL_SLIDER_5               1089
#define IDC_CTRL_EDIT_5                 1090
#define IDC_CTRL_LABEL_6                1091
#define IDC_CTRL_SLIDER_6               1092
#define IDC_CTRL_EDIT_6                 1093
#define IDC_CTRL_LABEL_7                1094
#define IDC_CTRL_SLIDER_7               1095
#define IDC_CTRL_EDIT_7                 1096
#define ID_32772                        32772
#define ID_Menu                         32773
#define ID_MENU_ABOUT                   32774
#define ID_FILE_OPEN32775               32775
#define ID_MENU_COPY                    32776
#define ID_MENU_SELECTALL               32777
#define ID_MENU_CLEAR                   32778
#define ID_TOOLS_CONTROLS               32779
#define ID_Menu32780                    32780
#define ID_TOOLS_DATAINFO               32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
